apiVersion: v1
kind: Pod
metadata:
  name: devmachine
spec:
  restartPolicy: Always
  containers:
  - name: devmachine
    image: debian
    resources:
      requests:
        cpu: 700m
        memory: 512Mi
      limits:
        cpu: 1250m
        memory: 1024Mi    
    command:
      - sleep
      - "3600"