apiVersion: v1
kind: Service
metadata:
  name: works-api-service
  namespace: testing
  labels:
    app: works-api
spec:
  type: ClusterIP
  selector:
    app: works-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
