apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: testing
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
          effect: NoSchedule
      containers:
        - name: api-gateway
          image: mbsakswetestaccacr.azurecr.io/buma-stemra-mono/api-gateway:107.0
          ports:
            - containerPort: 8080
          command:
            - node
            - '--require'
            - ./.pnp.cjs
            - ./src/main.js
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: api-gateway-configmap
