apiVersion: 'v1'
kind: 'ConfigMap'
metadata:
  namespace: 'testing'
  name: 'statement-api-configmap'
data:
  APP_ENV: '"acceptance"'
  NODE_ENV: '"production"'
  API_GATEWAY_URL: '"https://api.testing.k8s.bumastemra.nl"'
  PORTAL_URL: '"https://frontend.testing.k8s.bumastemra.nl"'
  PUPPETEER_EXECUTABLE_PATH: '"/home/gitlab/chromium/linux-1056772/chrome-linux/chrome"'
  PUPPETEER_ENABLED: 'false'
  SERVICE_CALL_TOKEN: '"${service-call-token}"'
  EXPRESS_REQUEST_TIMEOUT: '300000'
  SECRET_SALT: '"${secret-salt}"'
  JWT_PRIVATE_KEY: '"${jwt-private-key}"'
  JWT_PUBLIC_KEY: '"${jwt-public-key}"'
  SENTRY_ENABLED: 'true'
  PM2_MODE: '"cluster"'
  PM2_MERGE_LOGS: 'true'
  SSO_URL: '"https://login-acc.bumastemra.nl"'
  SSO_API_KEY: '"${sso-service-token}"'
  SSO_TENANT_ID: '"${sso-tenant-id}"'
  SSO_APPLICATIONS: '{"SetlistApp":"7df87155-34f1-4f29-9220-f4c70f4f86cf","MijnBumaStemra":"af634f5f-b884-4fc7-ab00-643ade2548fb","Backstage":"cb2c1078-49fe-432c-841b-08503dc05cd2","BumaStemraSSO":"3c219e58-ed0e-4b18-ad48-f4f92793ae32"}'
  DATABASE_HOST: '"mbs-postgresql-acc-01.postgres.database.azure.com"'
  DATABASE_PASSWORD: '"${postgres-password}"'
  DATABASE_USERNAME: '"${postgres-username}"'
  DATABASE_PORT: '5432'
  DATABASE_SSL_ENABLED: 'true'
  DATABASE_QUERY_DEBUG: 'false'
  DATABASE_PLATFORM_API_HOST: '"mbs-postgresql-acc-01.postgres.database.azure.com"'
  DATABASE_PLATFORM_API_NAME: '"platform_api"'
  DATABASE_PLATFORM_API_PASSWORD: '"${postgres-password}"'
  DATABASE_PLATFORM_API_USERNAME: '"${postgres-username}"'
  DATABASE_PLATFORM_API_PORT: '5432'
  DATABASE_PLATFORM_API_QUERY_DEBUG: 'false'
  DATABASE_PLATFORM_API_SSL_ENABLED: 'true'
  DATABASE_FUSIONAUTH_HOST: '"mbs-postgresql-acc-01.postgres.database.azure.com"'
  DATABASE_FUSIONAUTH_NAME: '"fusionauth"'
  DATABASE_FUSIONAUTH_PASSWORD: '"${postgres-password}"'
  DATABASE_FUSIONAUTH_USERNAME: '"${postgres-username}"'
  DATABASE_FUSIONAUTH_PORT: '5432'
  DATABASE_FUSIONAUTH_QUERY_DEBUG: 'false'
  DATABASE_FUSIONAUTH_SSL_ENABLED: 'true'
  GRAPHQL_PLAYGROUND_ENABLED: 'true'
  GRAPHQL_INTROSPECTION_ENABLED: 'true'
  GRAPHQL_DEPTH_LIMIT: '10'
  SUISA_URI: '"https://apitest.ipisystem.org/cxf/Change_v1?wsdl"'
  SUISA_USERNAME: '"${suisa-username}"'
  SUISA_PASSWORD: '"${suisa-password}"'
  KAFKA_CONSUMER_BROKERS: '["kafka-workers-acc.int.bumastemra.nl:9092"]'
  KAFKA_PRODUCER_BROKERS: '["kafka-workers-acc.int.bumastemra.nl:9092"]'
  KAFKA_PRODUCER_TOPIC_PLATFORM: '"ACCEPTANCE_PLATFORM"'
  KAFKA_PRODUCER_TOPIC_MAIN: '"ACCEPTANCE_MAIN"'
  KAFKA_PRODUCER_TOPIC_NAW: '"ACCEPTANCE_NAW"'
  KAFKA_PRODUCER_TOPIC_SETLISTS: '"ACCEPTANCE_PLATFORM"'
  KAFKA_PRODUCER_SAVE_PATH: '"/tmp/mbs-kafka"'
  POSTMARK_SERVER_API_TOKEN: '"${postmark-server-api-token}"'
  SIGNHOST_URL: '"https://api.signhost.com/api"'
  SIGNHOST_AUTHORIZATION: '"${signhost-api-key}"'
  SIGNHOST_APPLICATION: '"${signhost-app-key}"'
  REDIS_HOST: '"mbs-redis-acc.int.bumastemra-otc.nl"'
  REDIS_PASSWORD: '"${redis-access-key}"'
  REDIS_PORT: '6379'
  REDIS_DB_INDEX_FILE_SERVICE: '0'
  REDIS_DB_INDEX_FLOOD_SERVICE: '1'
  AZURE_STORAGE_CONFIG: '[{"name":"deprecated-storage","type":"blob","account":"bsotcweadcastd02","sasToken":"${mbs-blob-sas-token-soundfiles}","services":[{"name":"soundfiles","service":"bsotcweadcastd02container"}]},{"name":"mbs-storage","type":"blob","sasToken":"${azure-blob-mbs-storage-sas-token}","account":"mbsstorageacc","services":[{"name":"work-agreements","service":"work-agreements"},{"name":"setlists","service":"setlists"},{"name":"cession-assignments","service":"cession-assignments"},{"name":"membership-registration","service":"membership-registration"},{"name":"beat","service":"beat"}]},{"name":"mbs-storage-sound-files","type":"blob","sasToken":"${azure-blob-mbs-storage-sas-token}","account":"mbsstorageacc","services":[{"name":"sound-files","service":"sound-files"}]},{"name":"mbs-fileservice","type":"blob","account":"mbsfileserviceacc","sasToken":"${fileservice-blob-access-key}","services":[{"name":"works-service","service":"works-service"},{"name":"statement-service","service":"statement-service"},{"name":"user-service","service":"user-service"}]},{"name":"mbs-fileshare","type":"fileshare","account":"mbsportaldocacc","sasToken":"${azure-fileshares-mbs-statement-documents-sas-token}","services":[{"name":"published-documents","service":"mbsportaldocsacc"}]}]'
  PM2_NAME: '"statement-service-api"'
  PM2_INSTANCES: '2'
  PM2_SCRIPT: '"./api/main.js"'
  PM2_INTERPRETER_ARGS: '"--require /var/www/apps/statement-service-api/.pnp.cjs  --max-http-header-size'
  SENTRY_DSN: '"https://f400a4d4ad894fd8bb540e877191ef60@sentry.bumastemra.nl/30"'
  PLATFORM_SERVICE_API_URL: '"http://platform-api-service:8080/v1"'
  PORT: '8080'
  FILESERVICE_DISTRIBUTIONS_EXPORT_QUEUE: '"statement-distributions-export"'
  DATABASE_NAME: '"finance"'
  PLATFORM_API_SERVICE_TOKEN: '"${platform-api-service-token}"'
  PLATFORM_API_SECURITY_TOKEN: '"${platform-api-security-token}"'
  SIGNHOST_POSTBACK_URL: '"https://api-acc.bumastemra.nl/statements/cessions/signhost"'
